"""empty message

Revision ID: bcd41de3cf7e
Revises: bfbaf6c22229
Create Date: 2018-01-01 18:23:18.012844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd41de3cf7e'
down_revision = 'bfbaf6c22229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ihome_house_facility',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['ihome_facility.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['ihome_house.id'], ),
    sa.PrimaryKeyConstraint('house_id', 'facility_id')
    )
    op.add_column(u'ihome_user', sa.Column('pwd_hash', sa.String(length=200), nullable=True))
    op.alter_column(u'ihome_user', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column(u'ihome_user', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.drop_column(u'ihome_user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'ihome_user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
    op.alter_column(u'ihome_user', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column(u'ihome_user', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column(u'ihome_user', 'pwd_hash')
    op.drop_table('ihome_house_facility')
    # ### end Alembic commands ###
