"""empty message

Revision ID: fada65a4d7b1
Revises: b7c9fd3634d3
Create Date: 2017-12-29 18:28:49.763291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fada65a4d7b1'
down_revision = 'b7c9fd3634d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user', sa.Column('id_name', sa.String(length=32), nullable=True))
    op.add_column('ihome_user', sa.Column('phone', sa.String(length=11), nullable=False))
    op.drop_index('mobile', table_name='ihome_user')
    op.create_unique_constraint(None, 'ihome_user', ['id_card'])
    op.create_unique_constraint(None, 'ihome_user', ['phone'])
    op.drop_column('ihome_user', 'mobile')
    op.drop_column('ihome_user', 'real_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user', sa.Column('real_name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('ihome_user', sa.Column('mobile', mysql.VARCHAR(length=11), nullable=False))
    op.drop_constraint(None, 'ihome_user', type_='unique')
    op.drop_constraint(None, 'ihome_user', type_='unique')
    op.create_index('mobile', 'ihome_user', ['mobile'], unique=True)
    op.drop_column('ihome_user', 'phone')
    op.drop_column('ihome_user', 'id_name')
    # ### end Alembic commands ###
